/**************************************************************************
*                                                                         *
*                                                                         *
*                                                                         *
*                                                                         *
*                                                                         *
*                                                                         *
**************************************************************************/
#include<iostream.h>
#include<conio.h>
void disp(int i=0)
{
 cout<<"\n I am int output";
}
void disp(char a)
{
 cout<<"\n i am character output";
}
void main()
{
int a,b,c;
clrscr();
disp();
getch();
}
